version: "3.9"

services:
  db:
    image: ghcr.io/${REPO}/db:${IMAGE_TAG}
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    secrets:
      - source: db_password
        target: db_password
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d forum"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    image: ghcr.io/${REPO}/api:${IMAGE_TAG}
    environment:
      DB_HOST: db
      DB_NAME: forum
      DB_USER: postgres
      DB_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - backend
      - frontend
    secrets:
      - source: db_password
        target: db_password
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  front:
    image: ghcr.io/${REPO}/front:${IMAGE_TAG}
    ports:
      - target: 80
        published: 80
        mode: host
    networks:
      - frontend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

secrets:
  db_password:
    external: true
    name: forum_db_password

volumes:
  db-data:
